Update files
chvg1968/goit-node-restapi pull request #3
Opened 2023-07-22 21:24 UTC by chvg1968

Update Files ( Controllers)

2023-07-22 22:17 UTC, Alonaklzh requested changes
todo funciona bien, excepto de put, no me deja hacer cambios, revisa su codigo y si necesitas ayuda, avisame

2023-07-22 22:44 UTC, chvg1968 commented
> todo funciona bien, excepto de put, no me deja hacer cambios, revisa su codigo y si necesitas ayuda, avisame

Hola profe, a mi si me funciona, lo comprobé con Postman. Acá le dejo las imágenes capturas de PUT y GET desde Postman para que pueda verificar que si se actualiza la base de datos. [https://ibb.co/RYWdz2v](url),
[https://ibb.co/bXX1NbG](url)

2023-07-23 09:11 UTC, Alonaklzh commented
parece que era un bug en postman,ahora funciona bien

2023-07-23 09:12 UTC, Alonaklzh approved these changes

2023-07-23 09:12 UTC, merged